-- Quarantine leads whose contact details were never sourced from anywhere real.
--
-- Three functions used to ask a language model to produce businesses, complete
-- with plausible +254 phone numbers and inferred email addresses, and insert
-- them as status 'qualified':
--
--   ai-discover      generated leads outright                 (deleted)
--   discover-leads   fell back to generation without Firecrawl (removed)
--   social-discover  generated when a platform search was empty (removed)
--
-- The code paths are gone, but the rows they wrote are still here and still
-- reachable by every sender. This adds an explicit provenance state and
-- backfills it, so nothing invented can be contacted again.

-- ---------------------------------------------------------------------------
-- 1. The column
-- ---------------------------------------------------------------------------

ALTER TABLE public.leads
  ADD COLUMN IF NOT EXISTS verification_state text NOT NULL DEFAULT 'unverified';

ALTER TABLE public.leads
  DROP CONSTRAINT IF EXISTS leads_verification_state_check;

ALTER TABLE public.leads
  ADD CONSTRAINT leads_verification_state_check
  CHECK (verification_state IN ('rejected', 'unverified', 'verified'));

COMMENT ON COLUMN public.leads.verification_state IS
  'Provenance of this lead''s contact details. '
  'rejected = known to have been generated by a model, never contact. '
  'unverified = provenance unknown or unconfirmed, needs review before contact. '
  'verified = came from an external search result. '
  'Senders must require ''verified''.';

-- ---------------------------------------------------------------------------
-- 2. Backfill by discovery_source
--
--    web, google_maps  -> came from a Firecrawl search result, so there was a
--                         real page behind them. Treated as verified.
--    ai_search         -> produced by ai-discover, or by discover-leads'
--                         generative fallback. Provably fabricated.
--    instagram, tiktok -> social-discover wrote BOTH scraped and generated
--                         leads under these same values, so they cannot be
--                         told apart after the fact. Held for review rather
--                         than trusted or destroyed.
--    anything else     -> unknown provenance, same treatment.
-- ---------------------------------------------------------------------------

UPDATE public.leads
SET    verification_state = 'verified'
WHERE  discovery_source IN ('web', 'google_maps');

UPDATE public.leads
SET    verification_state = 'rejected'
WHERE  discovery_source = 'ai_search';

UPDATE public.leads
SET    verification_state = 'unverified'
WHERE  discovery_source IS NULL
   OR  discovery_source NOT IN ('web', 'google_maps', 'ai_search');

-- ---------------------------------------------------------------------------
-- 3. Indexes
--
--    Every sender filters leads by user, status and now verification_state,
--    then orders by priority_score. The table had no indexes at all, so this
--    is also the first one.
-- ---------------------------------------------------------------------------

CREATE INDEX IF NOT EXISTS leads_user_sendable_idx
  ON public.leads (user_id, verification_state, status, priority_score DESC);

CREATE INDEX IF NOT EXISTS leads_user_discovery_source_idx
  ON public.leads (user_id, discovery_source);
